#!/bin/bash

SERVICE="http://localhost:8123/ping"

MONITOR="$1"
ACTION="$2"

if [ -z "$MONITOR" -o -z "$ACTION" ]; then
    echo 1>&2 "Must provide monitor and action"
    exit 1
fi

case "$ACTION" in
    "reload" )
        hard=
        if [ -n "$3" ]; then
            hard="$3"
        fi

        curl -d hard="$hard" "$SERVICE/$MONITOR/reload"
        ;;
    "url" )
        if [ -z "$3" ]; then
            echo 1>&2 "Must proivde URL"
            exit 1
        fi

        url="$3"

        curl -d url="$url" "$SERVICE/$MONITOR/url"
        ;;
esac
